# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'clearingPrototypeContainerRegistry'
    azureResourceGroup: 'clearing-prototype-rg'
    kubernetesCluster: 'clearing-prototype'
    command: 'package'
    chartPath: 'charts/clearing-prototype-client'

- task: Docker@2
  inputs:
    containerRegistry: 'clearingregistry'
    repository: 'clearing-proto-client'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'clearing-prototype-client'
    publishLocation: 'Container'