apiVersion: v1
kind: Service
metadata:
  name: clearing-prototype-client
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: clearing-prototype-client
  ports:
  - name: app
    protocol: TCP
    port: 8100
    targetPort: 4200